version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
